disabled_rules:
  - force_cast
  - line_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - missing_docs

variable_name:
  min_length:
    warning: 0
    error: 0

excluded:
  - Pods
  - .gems
